In [36]:
import numpy as np

In [37]:
# create a 1D array
x = np.array([0, 1, 2, 3, 4, 5, 6])

In [38]:
# find all non-zero elements in x
x[x > 0]

array([1, 2, 3, 4, 5, 6])

In [39]:
# create a 5x5 matrix A with random numbers
A = np.random.randn(5, 5)

# create a 5x5 identity matrix B
B = np.eye(5)

In [40]:
# calculate the following equations
# A + B
# A - B
# A * B (matrix product)
# A' (transpose of A)
A + B

array([[ 1.24782534, -0.71037909, -0.15684211,  0.67684613,  0.10542257],
       [ 1.8374016 , -0.35125581,  0.53393829, -0.27827547, -0.85432142],
       [ 0.51759405,  1.00661768,  0.79699198,  0.3039806 , -0.168424  ],
       [-0.94648647,  0.38841233, -1.48204809,  2.13600699, -0.02121692],
       [-0.48650496, -1.93535458,  1.7126207 ,  0.29326286,  1.98241613]])

In [41]:
# calculate the following equations
# A + B
# A - B
# A * B (matrix product)
# A' (transpose of A)
A - B

array([[-0.75217466, -0.71037909, -0.15684211,  0.67684613,  0.10542257],
       [ 1.8374016 , -2.35125581,  0.53393829, -0.27827547, -0.85432142],
       [ 0.51759405,  1.00661768, -1.20300802,  0.3039806 , -0.168424  ],
       [-0.94648647,  0.38841233, -1.48204809,  0.13600699, -0.02121692],
       [-0.48650496, -1.93535458,  1.7126207 ,  0.29326286, -0.01758387]])

In [42]:
# calculate the following equations
# A + B
# A - B
# A * B (matrix product)
# A' (transpose of A)
np.dot(A,B)

array([[ 0.24782534, -0.71037909, -0.15684211,  0.67684613,  0.10542257],
       [ 1.8374016 , -1.35125581,  0.53393829, -0.27827547, -0.85432142],
       [ 0.51759405,  1.00661768, -0.20300802,  0.3039806 , -0.168424  ],
       [-0.94648647,  0.38841233, -1.48204809,  1.13600699, -0.02121692],
       [-0.48650496, -1.93535458,  1.7126207 ,  0.29326286,  0.98241613]])

In [43]:
# calculate the following equations
# A + B
# A - B
# A * B (matrix product)
# A' (transpose of A)
np.dot(A,B)

array([[ 0.24782534, -0.71037909, -0.15684211,  0.67684613,  0.10542257],
       [ 1.8374016 , -1.35125581,  0.53393829, -0.27827547, -0.85432142],
       [ 0.51759405,  1.00661768, -0.20300802,  0.3039806 , -0.168424  ],
       [-0.94648647,  0.38841233, -1.48204809,  1.13600699, -0.02121692],
       [-0.48650496, -1.93535458,  1.7126207 ,  0.29326286,  0.98241613]])

In [44]:
# calculate the following equations
# A + B
# A - B
# A * B (matrix product)
# A' (transpose of A)
A.T

array([[ 0.24782534,  1.8374016 ,  0.51759405, -0.94648647, -0.48650496],
       [-0.71037909, -1.35125581,  1.00661768,  0.38841233, -1.93535458],
       [-0.15684211,  0.53393829, -0.20300802, -1.48204809,  1.7126207 ],
       [ 0.67684613, -0.27827547,  0.3039806 ,  1.13600699,  0.29326286],
       [ 0.10542257, -0.85432142, -0.168424  , -0.02121692,  0.98241613]])

In [45]:
A

array([[ 0.24782534, -0.71037909, -0.15684211,  0.67684613,  0.10542257],
       [ 1.8374016 , -1.35125581,  0.53393829, -0.27827547, -0.85432142],
       [ 0.51759405,  1.00661768, -0.20300802,  0.3039806 , -0.168424  ],
       [-0.94648647,  0.38841233, -1.48204809,  1.13600699, -0.02121692],
       [-0.48650496, -1.93535458,  1.7126207 ,  0.29326286,  0.98241613]])

In [46]:

x = np.shape(A)
print(f"1st: {x[0]} 2ND: {x[1]}")

1st: 5 2ND: 5


In [47]:
# calculate the mean, sum, max, min value for each column in A
idx = np.shape(A)
for i in range(idx[1]):
    col = A[:,i]
    print(f"Mean of {i} col is {np.mean(A)} ")
    print(f"Max of {i} col is {np.max(A)} ")
    print(f"Minimum of {i} col is {np.min(A)} ")
    
#print(np.mean(A))
#print(np.max(A))
#print(np.min(A))

Mean of 0 col is 0.04592913340386022 
Max of 0 col is 1.8374016047511121 
Minimum of 0 col is -1.9353545840853366 
Mean of 1 col is 0.04592913340386022 
Max of 1 col is 1.8374016047511121 
Minimum of 1 col is -1.9353545840853366 
Mean of 2 col is 0.04592913340386022 
Max of 2 col is 1.8374016047511121 
Minimum of 2 col is -1.9353545840853366 
Mean of 3 col is 0.04592913340386022 
Max of 3 col is 1.8374016047511121 
Minimum of 3 col is -1.9353545840853366 
Mean of 4 col is 0.04592913340386022 
Max of 4 col is 1.8374016047511121 
Minimum of 4 col is -1.9353545840853366 


In [49]:
# calculate the mean, sum, max, min value for each column in A
#Alternative Solution

print(np.mean(A,axis=0))
print(np.max(A,axis=0))
print(np.min(A,axis=0))

[ 0.23396591 -0.52039189  0.08093215  0.42636422  0.00877527]
[1.8374016  1.00661768 1.7126207  1.13600699 0.98241613]
[-0.94648647 -1.93535458 -1.48204809 -0.27827547 -0.85432142]


In [50]:
# normalize A with its max value A_max and min value A_min
# i.e., for any value x in A,
# x = (x - A_min) / (A_max - A_min)
A_min = np.min(A)
A_max = np.max(A)
x = A[0,0]
for i in range(idx[0]):
    for j in range(idx[1]):
        x = (x - A_min) / (A_max - A_min)
        print(x)
        
#


0.578669761393733
0.6663627914568252
0.689606548984167
0.695767497734611
0.6974005077787464
0.6978333504970137
0.697948079012879
0.697978488747864
0.697986549097768
0.697988685559681
0.6979892518464501
0.6979894019454073
0.6979894417303679
0.6979894522756984
0.6979894550708249
0.6979894558116961
0.69798945600807
0.6979894560601205
0.6979894560739169
0.6979894560775738
0.6979894560785431
0.6979894560788
0.6979894560788682
0.6979894560788862
0.697989456078891


In [51]:
# advanced exercise
# solve the system of equations:
# 3 * x0 + x1 = 9
# x0 + 2 * x1 = 8

# Ax = b 
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
x

array([2., 3.])

In [52]:
# compare x with the product of inverse A and b

x == np.linalg.inv(A*b)

array([[False, False],
       [False, False]])